### ISSUE TITLE
remove query string 

### ISSUE THREAD

**Issue by Ganyu69** [mihdan/mihdan-no-external-links#31]
example

https://domain.com/goto/aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2ZhY2Vib29r?swcfpc=1

end up to 404  https://www.facebook.com/facebook%B3%07%1F%A5%CD

**Comment by Ganyu69** [comment]
error if not using cloudflare ![image](https://github.com/mihdan/mihdan-no-external-links/assets/78007658/41f8c2fa-7eb3-453c-a135-f3ef7535978a)

**Comment by mihdan** [comment]
Hi

Check the error logs of your webserver

**Comment by Ganyu69** [comment]
@mihdan 

![Screenshot 2023-05-16 000925](https://github.com/mihdan/mihdan-no-external-links/assets/78007658/a2728c5c-86aa-4f9a-9c1c-c886a8be9c59)

nginx: 
`2023/05/15 17:44:16 [error] 920934#920934: *507345 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "Mihdan\No_External_Links\Mihdan_NoExternalLinks_Database" not found in /home/test/web/domain.com/public_html/wp-content/plugins/mihdan-no-external-links/public/Frontend.php:988
Stack trace:
#0 /home/test/web/domain.com/public_html/wp-content/plugins/mihdan-no-external-links/public/Frontend.php(474): Mihdan\No_External_Links\Frontend->add_log()
#1 /home/test/web/domain.com/public_html/wp-content/plugins/mihdan-no-external-links/public/Frontend.php(428): Mihdan\No_External_Links\Frontend->redirect()
#2 /home/test/web/domain.com/public_html/wp-includes/class-wp-hook.php(308): Mihdan\No_External_Links\Frontend->check_redirect()
#3 /home/test/web/domain.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /home/test/web/domain.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/test/web/domain.com/public_html/wp-includes/template-loader.php(13): do_action()
#6 /home/test/web/domain.com/public" while reading response header from upstream, client: xx.xx.xx.xx, server: domain.com, request: "GET /url/aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2ZhY2Vib29r?hello HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.2-fpm-domain.com.sock:", host: "domain.com"`

the error only appears if there is a query string

**Comment by mihdan** [comment]
Did you install the plugin from the WordPress repository or from GitHub?

**Comment by Ganyu69** [comment]
WordPress repository 

`Version 5.0.7`
